all:
  children:
    web:
      hosts:
        # This gets populated by terraform output during deployment
        web1:
          ansible_host: 54.174.40.253
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      vars:
        # Web server specific variables
        nginx_port: 80
        nginx_ssl_port: 443
        document_root: /var/www/html
  vars:
    # Security hardening
    ssh_port: 22
    disable_root_login: true
    enable_ufw_firewall: true
    
    # System configuration
    timezone: UTC
    ntp_enabled: true
    
    # Monitoring and logging
    cloudwatch_agent_enabled: true
    log_retention_days: 7