# Static inventory template - will be populated by Terraform outputs
# or dynamic inventory from AWS EC2 instances

all:
  children:
    web:
      hosts:
        # This will be populated dynamically from Terraform outputs
        # or via AWS EC2 dynamic inventory
        web1:
          ansible_host: "{{ terraform_outputs.web_instance_public_ip | default('127.0.0.1') }}"
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          instance_id: "{{ terraform_outputs.web_instance_id | default('') }}"
          environment: "{{ terraform_outputs.environment | default('dev') }}"
      vars:
        # Web server specific variables
        nginx_port: 80
        nginx_ssl_port: 443
        server_name: "{{ ansible_host }}"
        document_root: /var/www/html

# Group variables for all hosts
all:
  vars:
    # Security hardening
    ssh_port: 22
    disable_root_login: true
    enable_ufw_firewall: true
    
    # System configuration
    timezone: UTC
    ntp_enabled: true
    
    # Monitoring and logging
    cloudwatch_agent_enabled: true
    log_retention_days: 7