---
- name: Install nginx
  package:
    name: nginx
    state: present
  become: yes

- name: Ensure nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  notify: restart nginx

- name: Create web root directory
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: yes

- name: Deploy custom index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  become: yes
  notify: restart nginx

- name: Configure nginx security headers
  template:
    src: security-headers.conf.j2
    dest: /etc/nginx/conf.d/security-headers.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart nginx

- name: Configure nginx main site
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart nginx

- name: Enable nginx main site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes
  notify: restart nginx

- name: Test nginx configuration
  command: nginx -t
  become: yes
  changed_when: false

- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
  become: yes